import tkinter as tk
from tkinter import ttk, messagebox, font
import webbrowser
import os

# --- Modern Professional Palette ---
COLOR_BG_DEEP = "#0f0f17"      # Darker Base
COLOR_BG_SURFACE = "#16161e"   # Sidebar/Surface
COLOR_BG_OVERLAY = "#1f1f28"   # Field background
COLOR_TEXT_MAIN = "#dcd7ba"    # Creamy Text
COLOR_TEXT_SUB = "#727169"     # Dimmed Text
COLOR_ACCENT_BLUE = "#7e9cd8"  # Professional Blue
COLOR_ACCENT_TEAL = "#7aa89f"  # Soft Teal
COLOR_ACCENT_RED = "#c34043"   # Muted Red
COLOR_ACCENT_MAUVE = "#957fb8" # Lavender

GITHUB_URL = "https://github.com/cheetahcoder"

def generate_js_code():
    try:
        courses_raw = courses_entry.get().strip()
        hours = hour_spinbox.get()
        minutes = minute_spinbox.get()
        seconds = second_spinbox.get()
        global_delay = global_delay_var.get()
        retry_delay = retry_delay_var.get()

        if not courses_raw:
            show_status("Error: No course codes entered.", COLOR_ACCENT_RED)
            return

        course_list = [c.strip() for c in courses_raw.replace('،', ',').split(',') if c.strip()]
        js_course_array = str(course_list)

        # Doubling all curly braces {{ }} for JS logic to prevent Python f-string errors.
        js_code = f"""/**
 * --- Generated by RegSniper v4.1 (Schedule Sync Edition) ---
 * Target Schedule: {hours.zfill(2)}:{minutes.zfill(2)}:{seconds.zfill(2)}
 * Strategy: Direct Fetch API + Advanced Success Detection
 */

window.stopSniper = false;
let myCourseNumbers = {js_course_array}; 
const targetTime = new Date();
targetTime.setHours({hours}, {minutes}, {seconds}, 0); 

const GLOBAL_DELAY = {global_delay};
const COURSE_LIMIT_MS = {retry_delay};

const toPersian = (num) => num.toString().replace(/\\d/g, d => '۰۱۲۳۴۵۶۷۸۹'[d]);
const lastAttempt = {{}};

const showNotification = (message, color = "#7aa89f") => {{
    const toast = document.createElement('div');
    toast.innerText = message;
    toast.style = `position: fixed; top: 20px; right: 20px; background: ${{color}}; color: #0f0f17; 
                   padding: 15px 25px; border-radius: 8px; font-family: Tahoma, sans-serif; 
                   z-index: 999999; font-weight: bold; box-shadow: 0 4px 15px rgba(0,0,0,0.3);
                   transition: opacity 0.5s ease; direction: rtl;`;
    document.body.appendChild(toast);
    setTimeout(() => {{ 
        toast.style.opacity = '0'; 
        setTimeout(() => toast.remove(), 500); 
    }}, 4000);
}};

const getAuthToken = () => {{
    const jwtRegex = /eyJ[a-zA-Z0-9-_]+\\.[a-zA-Z0-9-_]+\\.[a-zA-Z0-9-_]+/;
    const storages = [localStorage, sessionStorage];
    for (const storage of storages) {{
        for (let i = 0; i < storage.length; i++) {{
            const key = storage.key(i);
            const val = storage.getItem(key);
            if (!val) continue;
            const match = val.match(jwtRegex);
            if (match) return match[0];
        }}
    }}
    const cookieMatch = document.cookie.match(jwtRegex);
    if (cookieMatch) return cookieMatch[0];
    return null;
}};

async function sendRegistrationRequest(courseIdWithGroup, units, row) {{
    const token = getAuthToken();
    if (!token) {{
        showNotification("خطا: توکن پیدا نشد!", "#c34043");
        return "NO_TOKEN";
    }}

    const payload = {{
        id: crypto.randomUUID(),
        action: "add",
        course: courseIdWithGroup, 
        units: parseInt(units) || 1
    }};

    console.log(`%c[Sniper] 🚀 Requesting: ${{courseIdWithGroup}}`, "color: #7e9cd8", payload);

    try {{
        const response = await fetch('https://my.edu.sharif.edu/api/reg', {{
            method: 'POST',
            headers: {{
                'Authorization': token,
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }},
            body: JSON.stringify(payload)
        }});
        
        const data = await response.json();
        
        // UPDATED SUCCESS LOGIC: 
        // If server returns "OK" OR a list of courses (which means schedule synced)
        const isSuccess = data.result === "OK" || (data.courses && Array.isArray(data.courses));

        if (isSuccess) {{
            console.log(`%c[Sniper] ✅ SUCCESS: ${{courseIdWithGroup}} Registered!`, "color: #a6e3a1; font-weight: bold");
            if (row) row.style.backgroundColor = "#eaffea";
            showNotification(`درس ${{courseIdWithGroup}} با موفقیت ثبت شد!`);
            return "OK";
        }} else {{
            const reason = data.result || data.error || JSON.stringify(data);
            console.warn(`%c[Sniper] ❌ FAILED: ${{courseIdWithGroup}} -> ${{reason}}`, "color: #f38ba8");
            return reason;
        }}
    }} catch (e) {{
        console.error(`[Sniper] ❌ Network Error`, e);
        return "NETWORK_ERROR";
    }}
}}

async function startEngine() {{
    console.log("%c[Sniper] Stealth API v4.1 Active.", "color: #cba6f7; font-weight: bold;");
    showNotification("اسنایپر آماده به کار است.");

    while (true) {{
        if (window.stopSniper || myCourseNumbers.length === 0) break;
        const now = Date.now();
        const rows = Array.from(document.querySelectorAll('tr'));

        for (let i = myCourseNumbers.length - 1; i >= 0; i--) {{
            const code = myCourseNumbers[i];
            const pCode = toPersian(code);
            const row = rows.find(r => r.innerText.includes(code) || r.innerText.includes(pCode));
            
            if (!row) continue;

            const isEnrolled = row.querySelector('.checkmark.icon') || row.classList.contains('positive');
            if (isEnrolled) {{
                console.log(`%c[Sniper] ✨ ${{code}} is already in your list.`, "color: #7aa89f");
                myCourseNumbers.splice(i, 1);
                continue; 
            }}

            if (!lastAttempt[code] || (now - lastAttempt[code] > COURSE_LIMIT_MS)) {{
                // 1. Determine Full Course-Group ID
                let courseIdWithGroup = code; 
                const groupRegex = new RegExp(code + "-\\\\d+");
                const match = row.innerText.match(groupRegex);
                courseIdWithGroup = match ? match[0] : code + "-1";

                // 2. Unit Extraction
                let units = 1;
                const cells = Array.from(row.querySelectorAll('td'));
                for (const cell of cells) {{
                    const val = cell.innerText.trim();
                    if (/^[1-4]$/.test(val)) {{
                        units = parseInt(val);
                        break;
                    }}
                }}

                lastAttempt[code] = now;
                const res = await sendRegistrationRequest(courseIdWithGroup, units, row);
                
                if (res === "OK") {{
                    const jitter = Math.floor(Math.random() * 300) - 150;
                    await new Promise(r => setTimeout(r, GLOBAL_DELAY + jitter));
                }} else if (res === "REGISTRATION_TIME_LIMIT") {{
                    lastAttempt[code] = Date.now() - (COURSE_LIMIT_MS - 400);
                }}
            }}
        }}
        await new Promise(r => setTimeout(r, 600));
    }}
}}

const timeToLaunch = targetTime.getTime() - Date.now();
if (timeToLaunch > 0) {{
    console.log(`[Sniper] Armed. Waiting for target time...`);
    setTimeout(startEngine, timeToLaunch);
}} else {{
    startEngine();
}}
"""
        output_text.config(state="normal")
        output_text.delete("1.0", tk.END)
        output_text.insert("1.0", js_code.strip())
        output_text.config(state="disabled")
        
        if autocopy_var.get():
            root.clipboard_clear()
            root.clipboard_append(output_text.get("1.0", tk.END).strip())
            show_status(f"v4.1 Ready & Copied.", COLOR_ACCENT_TEAL)
        else:
            show_status(f"v4.1 Ready.", COLOR_ACCENT_TEAL)

    except Exception as e:
        show_status(f"Error: {e}", COLOR_ACCENT_RED)

def copy_to_clipboard():
    code = output_text.get("1.0", tk.END).strip()
    if code:
        root.clipboard_clear()
        root.clipboard_append(code)
        show_status("Copied to clipboard!", COLOR_ACCENT_BLUE)

def show_status(message, color):
    status_label.config(text=message, fg=color)

def open_github(event):
    webbrowser.open_new_tab(GITHUB_URL)

# --- GUI Setup ---
root = tk.Tk()
root.title("RegSniper v4.1 Pro")
root.geometry("950x680")
root.configure(bg=COLOR_BG_DEEP)

# Window Icon Logic
script_dir = os.path.dirname(os.path.abspath(__file__))
icon_path = os.path.join(script_dir, "app_icon.png")
if os.path.exists(icon_path):
    try:
        app_icon = tk.PhotoImage(file=icon_path)
        root.iconphoto(True, app_icon)
    except: pass

style = ttk.Style()
style.theme_use('clam')
style.configure("TSpinbox", fieldbackground=COLOR_BG_OVERLAY, background=COLOR_BG_OVERLAY, foreground=COLOR_TEXT_MAIN, borderwidth=0)

main_container = tk.Frame(root, bg=COLOR_BG_DEEP)
main_container.pack(fill="both", expand=True)

# Sidebar
sidebar = tk.Frame(main_container, bg=COLOR_BG_SURFACE, width=340, padx=30, pady=25)
sidebar.pack(side="left", fill="y")
sidebar.pack_propagate(False)

tk.Label(sidebar, text="REG SNIPER", font=("Segoe UI Black", 26), fg=COLOR_ACCENT_MAUVE, bg=COLOR_BG_SURFACE).pack(anchor="w", pady=(0, 2))
tk.Label(sidebar, text="Sharif Edition v4.1", font=("Segoe UI", 10), fg=COLOR_TEXT_SUB, bg=COLOR_BG_SURFACE).pack(anchor="w", pady=(0, 25))

def create_label(parent, text, color=COLOR_ACCENT_BLUE):
    lbl = tk.Label(parent, text=text, font=("Segoe UI Black", 9), fg=color, bg=COLOR_BG_SURFACE)
    lbl.pack(anchor="w", pady=(12, 4))
    return lbl

create_label(sidebar, "TARGET COURSE CODES")
courses_entry = tk.Entry(sidebar, bg=COLOR_BG_OVERLAY, fg=COLOR_TEXT_MAIN, insertbackground="white", font=("Consolas", 11), borderwidth=0, highlightthickness=1, highlightbackground=COLOR_BG_OVERLAY)
courses_entry.pack(fill="x", ipady=8)
courses_entry.insert(0, "52115, 52124")

create_label(sidebar, "SCHEDULE (HH:MM:SS)")
time_frame = tk.Frame(sidebar, bg=COLOR_BG_SURFACE)
time_frame.pack(fill="x")

spin_opts = {"width": 4, "format": "%02.0f", "font": ("Segoe UI", 12, "bold"), "background": COLOR_BG_OVERLAY}
hour_spinbox = ttk.Spinbox(time_frame, from_=0, to=23, **spin_opts); hour_spinbox.pack(side="left"); hour_spinbox.set("08")
tk.Label(time_frame, text=":", font=("Segoe UI", 14), fg=COLOR_TEXT_MAIN, bg=COLOR_BG_SURFACE).pack(side="left", padx=4)
minute_spinbox = ttk.Spinbox(time_frame, from_=0, to=59, **spin_opts); minute_spinbox.pack(side="left"); minute_spinbox.set("00")
tk.Label(time_frame, text=":", font=("Segoe UI", 14), fg=COLOR_TEXT_MAIN, bg=COLOR_BG_SURFACE).pack(side="left", padx=4)
second_spinbox = ttk.Spinbox(time_frame, from_=0, to=59, **spin_opts); second_spinbox.pack(side="left"); second_spinbox.set("00")

create_label(sidebar, "STEALTH SETTINGS", COLOR_ACCENT_TEAL)
create_label(sidebar, "Global Interval (ms)", COLOR_TEXT_SUB)
global_delay_var = tk.IntVar(value=1800)
tk.Scale(sidebar, from_=1000, to=4000, variable=global_delay_var, orient="horizontal", bg=COLOR_BG_SURFACE, fg=COLOR_TEXT_MAIN, highlightthickness=0, troughcolor=COLOR_BG_DEEP, activebackground=COLOR_ACCENT_BLUE).pack(fill="x")

create_label(sidebar, "Course Retry (ms)", COLOR_TEXT_SUB)
retry_delay_var = tk.IntVar(value=16000)
tk.Scale(sidebar, from_=15500, to=25000, variable=retry_delay_var, orient="horizontal", bg=COLOR_BG_SURFACE, fg=COLOR_TEXT_MAIN, highlightthickness=0, troughcolor=COLOR_BG_DEEP, activebackground=COLOR_ACCENT_BLUE).pack(fill="x")

autocopy_var = tk.BooleanVar(value=True)
tk.Checkbutton(sidebar, text="Auto-copy to clipboard", variable=autocopy_var, bg=COLOR_BG_SURFACE, fg=COLOR_TEXT_MAIN, activebackground=COLOR_BG_SURFACE, font=("Segoe UI", 9)).pack(anchor="w", pady=(20, 0))

btn_gen = tk.Button(sidebar, text="GENERATE CODE", bg=COLOR_ACCENT_BLUE, fg=COLOR_BG_DEEP, font=("Segoe UI", 11, "bold"), command=generate_js_code, borderwidth=0, cursor="hand2")
btn_gen.pack(fill="x", pady=(30, 0), ipady=15)

footer_container = tk.Frame(sidebar, bg=COLOR_BG_SURFACE)
footer_container.pack(side="bottom", fill="x", pady=(10, 0))
github_link = tk.Label(footer_container, text="github.com/cheetahcoder", font=("Segoe UI", 9, "underline"), fg=COLOR_ACCENT_BLUE, bg=COLOR_BG_SURFACE, cursor="hand2")
github_link.pack(side="bottom"); github_link.bind("<Button-1>", open_github)
status_label = tk.Label(footer_container, text="System Ready", bg=COLOR_BG_SURFACE, fg=COLOR_TEXT_SUB, font=("Segoe UI Semibold", 9), wraplength=280)
status_label.pack(side="bottom", pady=(0, 5))

# Main Pane
content_area = tk.Frame(main_container, bg=COLOR_BG_DEEP, padx=35, pady=30)
content_area.pack(side="right", fill="both", expand=True)

tk.Label(content_area, text="GENERATED SNIPER LOGIC", font=("Segoe UI Black", 10), fg=COLOR_TEXT_SUB, bg=COLOR_BG_DEEP).pack(anchor="w", pady=(0, 15))
code_container = tk.Frame(content_area, bg=COLOR_BG_OVERLAY, padx=2, pady=2)
code_container.pack(expand=True, fill="both")
output_text = tk.Text(code_container, bg=COLOR_BG_SURFACE, fg=COLOR_TEXT_MAIN, font=("Consolas", 10), borderwidth=0, padx=20, pady=20, state="disabled", insertbackground="white")
output_text.pack(expand=True, fill="both")
btn_copy = tk.Button(content_area, text="MANUAL COPY", bg=COLOR_BG_SURFACE, fg=COLOR_ACCENT_MAUVE, font=("Segoe UI", 11, "bold"), command=copy_to_clipboard, borderwidth=1, highlightthickness=1, cursor="hand2")
btn_copy.pack(fill="x", pady=(20, 0), ipady=12)

if __name__ == "__main__":
    root.mainloop()